### PR TITLE
Ramp up viscosity slowly

### PR DESCRIPTION
**Pull request by GiudGiud**
Hey @AdrienWehrle 

I got some results with FV by ramping up velocity 1 order of magnitude per 1 order of magnitude.
I did it manually but you can do this programmatically by:
- making II_eps_min controllable (params.declareControlllable...)
- creating a FUnction that goes from 1e-10 to 1e-25 , over each time step (use a log obviously)
- use the RealFunctionControl with the function and the II eps min parameter

### CODE REVIEW

**Comment by GiudGiud** [comment]
Pressure looks great and velocity is peaking at the top at 1e-4 m/s so 300 m/year, still too fast?

**Comment by GiudGiud** [comment]
looking at the velocity results, they are still evolving, smoothly but evolving a long the X direction near the outlet. So the flow is not fully developed

**Comment by AdrienWehrle** [comment]
> Pressure looks great and velocity is peaking at the top at 1e-4 m/s so 300 m/year. It s close to our inlet velocity of 0.1 m/hr.

Thanks a lot, 300m/year sounds great, that's a pretty good order of magnitude for a glacier like this with no slip!

**Comment by GiudGiud** [comment]
I think what i did was more slowly ramping up diffusion than ramping it down. We have a ton of diffusion. I commented out the advective term eventually too

**Comment by AdrienWehrle** [comment]
> Pressure looks great and velocity is peaking at the top at 1e-4 m/s so 300 m/year. It s close to our inlet velocity of 0.1 m/hr.

That is 3km/year I think though, which is even better!

**Comment by AdrienWehrle** [comment]
> I commented out the advective term eventually too

What does that imply? I'm not sure I understand how that is affecting the results.

**Comment by GiudGiud** [comment]
It implies the flow is driven by a diffusive process rather than advection.
You can put it back in, you just may have to redo the ramp-up

I dont expect a big difference

**Comment by AdrienWehrle** [comment]
> looking at the velocity results, they are still evolving, smoothly but evolving a long the X direction near the outlet. So the flow is not fully developed

It looks great! What I'm not sure I understand is that although we prescribe a null velocity at the base,  I see non null values on the bottom boundary in Paraview. Is that the case for you too?

**Comment by AdrienWehrle** [comment]
> I got some results with FV by ramping up velocity 1 order of magnitude per 1 order of magnitude.

Maybe that's a strategy we could use to get the FE problem to converge on a better result too!

**Comment by GiudGiud** [comment]
> It looks great! What I'm not sure I understand is that although we prescribe a null velocity at the base, I see non null values on the bottom boundary in Paraview. Is that the case for you too?

null velocity is on the face, the value you see is a center-cell value in finite volume

**Comment by GiudGiud** [comment]
> Maybe that's a strategy we could use to get the FE problem to converge on a better result too!

I tried. Sadly no

**Comment by AdrienWehrle** [comment]
> > It looks great! What I'm not sure I understand is that although we prescribe a null velocity at the base, I see non null values on the bottom boundary in Paraview. Is that the case for you too?
> 
> null velocity is on the face, the value you see is a center-cell value in finite volume

Oh I see, thank you for the explanation!

**Comment by GiudGiud** [comment]
Make sure II_eps_min is a Real not a ADReal

**Comment by AdrienWehrle** [comment]
Thanks, that worked indeed, I still had it as ADReal in my header. 

I tried so many different setups with different `II_eps_min` but nothing would move the solution even slightly... Maybe an active nullspace removal would help, but probably I should just focus on the FV setup as we said.

**Pull request merged**
