### PR TITLE
Rampup viscosity through time in `icestream` FV to help convergence

### PR DESCRIPTION
**Pull request by AdrienWehrle**
As suggested by @GiudGiud in https://github.com/AdrienWehrle/diuca/pull/21, here I made `II_eps_min` controllable, and use a `RealFunctionControl` together with a `ParsedFunction` to prescribe an exponential decay of `II_eps_min` from 1e-10 down to 1e-21.

### CODE REVIEW

**Comment by AdrienWehrle** [comment]
Convergence is much harder when ice weight is not applied at the calving front (above water) but let free...!

**Comment by AdrienWehrle** [comment]
Do you also observe this @GiudGiud ? with pressure zero or 1 atmosphere at the front it starts not converging around ``II_eps_min = 1e-15``. I'll try and see if a slower exponential decay helps.

**Comment by GiudGiud** [comment]
I have not looked at that. I can see it being a more difficult problem to converge. The pressure has a jump at the outlet. 
And the real system has a 'wall' of fluid that should fall into the water

**Comment by AdrienWehrle** [comment]
> I have not looked at that. I can see it being a more difficult problem to converge. The pressure has a jump at the outlet. And the real system has a 'wall' of fluid that should fall into the water

Yes for now I still haven't managed to reach convergence with 0 or atmospheric pressure at z > 0 on the downstream boundary. The high values of the rampup converge, but it stops converging as soon as `II_eps_min` isn't restrictive anymore.  Investigating.

**Pull request merged**
